BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "vehicle-node"
BBFILE_PATTERN_vehicle-node = "^${LAYERDIR}/"
BBFILE_PRIORITY_vehicle-node = "6"

LAYERSERIES_COMPAT_vehicle-node = "kirkstone langdale mickledore nanbield scarthgap styhead walnascar"
